# Generated by Django 5.2.2 on 2025-06-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
